import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import NextTopLoader from "nextjs-toploader";
import SideBarContext from "@/components/SideBarContext/SideBarContext";

export const metadata: Metadata = {
  title: "Horizon UI Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return ( 
    <html lang="en">
      <body  className='w-screen flex justify-between bg-bg'>
      <NextTopLoader/>
  <SideBarContext/>
          {children}      
        </body>
    </html>
  );
}
